{% set name = "ethon" %}
{% set version = "0.15.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 0809805a035bc10f54162ca99f15ded49e428e0488bcfe1c08c821e18261a74d

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-ffi >=1.3.0

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: Very lightweight libcurl wrapper.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/typhoeus/{{ name }}

extra:
  recipe-maintainers:
    - sodre
