travis:
  secure:
    BINSTAR_TOKEN: Xi6jx0A51vwYqWuWNNIGeVhS3SqJWrTX3cuyfVYuU630rdTw/dGhbFYEu/b6krJcRrmJ1xEwknmow9iAQ1TrIFSFyWzLZB2cUKg+euZaTs4rjIgPtgVvrSSS7ciJCJxv33lo6FkEh3vSD3Z7xHDVlB9UzL29V4vZuyeqoPNebtwodNNNyhsvmdGkSexg9ILL/bcTzNCBk4u8XyfPe4joUAlzPdObuODfd0ud06DUGRNsl2o2nE9a5wI/yHPnK0W4B+LMYPBjOJh65fD9f3PdIfY3Jiq7cfDJwjBj4mJFbRjB7kWdoObR2GVUHmtdTdhXf+d2Kgb+dlpjotHz0kjXagBVliIb4tuKOhdcpGD7CryevhqMCnrc9qdE5qsgVr0+LS0gQRkjG/C6LcJ49UyIT84rxzYyks3wHJahiq8VCwoY1bnGcStbNRxDNaO7rh/pe0+ftqE4+UBlE/9Q1DtCf1NQeaXjCuWEN0LoqiggGU/mdOMHgwFxi2xB1ybUPqxpi9rowpUG5LyWT2bMPx+ERCxFNsQsut5D0vtizb1W8QlkhYIOBUQZzW6oObkkKP8vYOextU9TlVoex3N6Wb0BBlumoUrRGiWUWQKz+duZcQzKR2vxBLieZbymQ1rPaxjC/ep0n0XeGTsYbXdM2wCClhXPEmGxZ0jQRuxjpd8SX44=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
